@startuml

left to right direction

:Cliente: as c

(Meter dinero) as UC1
(Pedir azucar) as UC2
(Pedir producto) as UC3
(Cancelar) as UC4
(Devolver dinero) as UC5

c -- UC1
c -- UC2
c -- UC3
c -- UC4

UC3 ..> UC5 :<<include>>
UC4 ..> UC5 :<<include>>

@enduml